Stateless application
jrsalgado/nstsk pull request #17
Opened 2020-10-27 16:45 UTC by acambera-nearsoft

Stateless application changes

2020-10-27 17:02 UTC, jrsalgado requested changes

2020-10-27 17:02 UTC, jrsalgado commented on modules/database/main.tf
> +  name        = "rds-sg"
please use namespaced names [namespace]-[name] where make sense to be able to reuse the modules, like juniorh-rds-sg

2020-10-27 17:02 UTC, jrsalgado commented on modules/database/main.tf
> +  identifier_prefix      = "mysql-${var.app_env}"
identifier prefix can be something like "[namespace]-"

2020-10-27 17:02 UTC, jrsalgado commented on modules/ecs/files/user-data.sh
> +echo ECS_CLUSTER=${ecs_cluster} >> /etc/ecs/ecs.config
we can use terraform template files instead of echo to a file /etc/ecs/ecs.config

2020-10-27 17:02 UTC, jrsalgado commented on platform/stateless-application/backend.tf
> +    # key    = "nstask/Matillion"
herencia de un copy paste?

2020-11-04 23:26 UTC, acambera-nearsoft commented
@acambera-nearsoft testing

2020-11-05 15:46 UTC, joshuansu0897 commented
@acambera-nearsoft mention

2020-11-05 15:52 UTC, joshuansu0897 commented
@acambera-nearsoft mention two

2020-12-06 03:12 UTC, acambera-nearsoft commented on platform/stateless-application/backend.tf
> +    # key    = "nstask/Matillion"
done. fixed

2020-12-06 03:20 UTC, acambera-nearsoft commented on modules/database/main.tf
> +  name        = "rds-sg"
done. updated all the `name` to the suggested format.

2020-12-06 04:15 UTC, acambera-nearsoft commented on modules/ecs/files/user-data.sh
> +echo ECS_CLUSTER=${ecs_cluster} >> /etc/ecs/ecs.config
Replaced the redirect with a HEREDOC. The destination file is just one line.

Let me know what you think about it.

2020-12-06 22:08 UTC, acambera-nearsoft commented on modules/database/main.tf
> +  identifier_prefix      = "mysql-${var.app_env}"
fixed

2020-12-15 16:19 UTC, jrsalgado approved these changes

2020-12-15 16:19 UTC, jrsalgado commented on platform/stateless-application/main.tf
> +#module "elasticache" {
Si no lo necesitamos, es preferible quitarlo

2020-12-15 21:10 UTC, merged